### ISSUE TITLE
BTCClient.getBalance "Method not implemented"

### ISSUE THREAD

**Issue by venuswhispers** [xchainjs/xchainjs-lib#1047]
When I am using BTCClient.getBalance, some errors.
![Annotation 2024-02-18 171219](https://github.com/xchainjs/xchainjs-lib/assets/153607879/460f52bc-049b-4acb-af1c-cde53ff8c21a)

**Comment by venuswhispers** [comment]
Please help me.

**Comment by Thorian1te** [comment]
UTXO clients have several providers to retrieve the info the clients need and not all the providers return the same information. In your case, Bitgo provider only returns fee rates, so, when the client calls the getBalance and the round robin system is made, the warning appears
