### ISSUE TITLE
When I was about to get balance using getBalance.

### ISSUE THREAD

**Issue by venuswhispers** [xchainjs/xchainjs-lib#1048]
![Annotation 2024-02-18 172555](https://github.com/xchainjs/xchainjs-lib/assets/153607879/6aada11a-103e-4416-b7aa-be3e083497ee)
![Annotation 2024-02-18 172555](https://github.com/xchainjs/xchainjs-lib/assets/153607879/6aada11a-103e-4416-b7aa-be3e083497ee)
Sometimes, it happens.

**Comment by venuswhispers** [comment]
![Annotation 2024-02-18 172555](https://github.com/xchainjs/xchainjs-lib/assets/153607879/8d0a922b-68df-4c2b-8012-bde1ba50e939)

**Comment by 0xp3gasus** [comment]
It is due you are making too many request. A work around using many clients in cosmos-sdk will be created to fix the problem

**Comment by 0xp3gasus** [comment]
This issue can be closed. The workaround to work with several clients were applied in #1145
