### ISSUE TITLE
bug: estimate swap returns canSwap: true even tho there are errors

### ISSUE THREAD

**Issue by mikewyszinski** [xchainjs/xchainjs-lib#1075]
tried a swap and recevie the following response:
{
  "memo": "",
  "expiry": "2024-03-13T14:54:05.578Z",
  "toAddress": "",
  "txEstimate": {
    "input": "$ 200",
    "totalFees": {
      "asset": "ETH/DAI-0X6B175474E89094C44DA98B954EEDEAC495271D0F",
      "outboundFee": "ᚱ 0",
      "affiliateFee": "ᚱ 0"
    },
    "slipBasisPoints": "0",
    "netOutput": "0 DAI",
    "outboundDelaySeconds": 0,
    **"canSwap": true,
    "errors": [
      "Thornode request quote: failed to simulate swap: trading is halted, can't process swap"
    ]**
  }
}

suggest adding a sanity check to make sure the flag is correct like 
txDetails.memo.length > 0 && txDetails.txEstimate.errors.length === 0

**Comment by 0xp3gasus** [comment]
@mikewyszinski. I've trying to reproduce the error, but I could not, I need a little bit more of information. Can you provide the way you are making the request? Are you using the latest packages version?
