### ISSUE TITLE
Can't swap AVAX.USDC to RUNE

### ISSUE THREAD

**Issue by LongCX** [xchainjs/xchainjs-lib#1087]
As title. Pleae help me check
Error log:
```
{
  memo: '=:THOR.RUNE:thor1mx2wl3m527a5p870ldt0qehhq7ytxqsncuyyfv',
  expiry: 2024-03-20T06:19:01.000Z,
  toAddress: '0xd2cc1bbbb9ab48adb99f6d5bc6cc8ef11d99d25f',
  txEstimate: {
    input: '$ 1,000',
    totalFees: {
      asset: 'AVAX.USDC-0XB97EF9EF8734C71904D8002F8B6BC66DD9C48A6E',
      outboundFee: 'ᚱ 0.02',
      affiliateFee: 'ᚱ 0'
    },
    slipBasisPoints: '4',
    netOutput: 'ᚱ 136.844063',
    outboundDelaySeconds: 0,
    canSwap: false,
    errors: [ 'TC router has not been approved to spend this amount' ]
  }
}
```

**Comment by 0xp3gasus** [comment]
You need to approve the router first to be allowed to spend the desired amount in your name, so it is not a bug. What would be really interesting to avoid approve issues is to create that feature in ThorchainAMM, and approve the contract using ThorchainAMM, https://github.com/xchainjs/xchainjs-lib/issues/1088 has been created and I'll start working on it
