### ISSUE TITLE
Maya Package: Default natve TX fee should be 0.2 

### ISSUE THREAD

**Issue by GrassRootsCrypto** [xchainjs/xchainjs-lib#1179]
Within the Maya Package, change the Default Fee from 0.05 to 0.2.

This should reflect https://mayanode.mayachain.info/mayachain/mimir NATIVETRANSACTIONFEE

**Comment by Thorian1te** [comment]
at some point it was changed from https://github.com/xchainjs/xchainjs-lib/pull/934/files. 
```ts
 await axios.get<MayachainMimirResponse>(`${this.getClientUrl().node}/mayachain/mimir`) // Fetching NativeTransactionFee from https://mayanode.mayachain.info/mayachain/mimir
 ```
Same with thorchain I suppose.
