### ISSUE TITLE
Extract `validateAddress` into `XChainClient` interface 

### ISSUE THREAD

**Issue by veado** [xchainjs/xchainjs-lib#118]
- Add `validateAddress(address: Address): boolean` to `XChainClient
- Remove `validateAddress` from [BitcoinClient](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-bitcoin/src/client.ts#L33), [BinanceClient](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-binance/src/client.ts#L33), [CosmosClient](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-cosmos/src/client.ts#L30), [ThorchainClient](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain/src/client.ts#L30)
- Implement `validateAddress` to `asgardex-polkadot`

**Comment by junkai121** [comment]
Resolved by #149
