### ISSUE TITLE
Trade Assets

### ISSUE THREAD

**Issue by 0xp3gasus** [xchainjs/xchainjs-lib#1218]
Add support for Trade assets in THORChain

**Comment by Feedurhead-1** [comment]
Hello, we are having an issue trying to create a swap from trade asset to rune. We get a wrong string on the sent trade asset. 

thor.ltc as opposed to ltc˜ltc

https://runescan.io/tx/220CD1239193DC58AAC59DC6E7EA667C7BDAF4B527FE3C47971C0FD2E06ACED2

please advise. cheers.

**Comment by Feedurhead-1** [comment]
I have seen the PR, thanks in advance. Cheers.

**Comment by 0xp3gasus** [comment]
@Feedurhead-1 Trade asset support has not been release yet. Is it possible to share how you are making the swap?
