### ISSUE TITLE
is there solana sdk in xchainjs?

### ISSUE THREAD

**Issue by venuswhispers** [xchainjs/xchainjs-lib#1238]
how to use solana using xchainjs lib?

**Comment by bradstevens1** [comment]
Hello @venuswhispers 
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent
