### ISSUE TITLE
[Trade Assets]: Quoting swap is not working with affiliate fees

### ISSUE THREAD

**Issue by CW-75** [xchainjs/xchainjs-lib#1244]
Hi, I was trying to do some swaps using xchainjs including some affliate fees: and when I do a quote to `https://thornode.ninerealms.com/thorchain/quote/swap`. I've received this error:

```
{
  "error": "affiliate swap failed: fail to parse from address: 2 errors occurred:\n\t* internal error\n\t* decoding bech32 failed: invalid bech32 string length 4\n\n [gitlab.com/thorchain/thornode/x/thorchain/errors.go:73]"
}
```

### Request parameters & queries:

- `from_asset`: BCH~BCH
- `to_asset`: THOR.RUNE
- `amount`: 100000000
- `destination`: any Thor address
- `tolerance bps`: 1000
- `affiliate`: t
- `affiliate_bps`: 5

is this error cause internal errors during swaps? . I mean swaps with trades are working without affiliate fees but doing manually is throwing an `internal error` on the explorer. ref => https://runescan.io/tx/C83BC944C4371F9BC97EFF2E4587BF579D83F3FC19F25EF4A441BDC40FCFBA71

**Comment by Orion-9R** [comment]
I do think this is a thornode issue


[Errors] Here's quote request /w aff bps set to 5 

https://thornode.ninerealms.com/thorchain/quote/swap?from_asset=BCH~BCH&to_asset=THOR.RUNE&amount=100000000&destination=thor1ukwhpglu7yh2g2rw8h7jvee2r0fv0e90nyxv6v&tolerance_bps=1000&affiliate_bps=5&affiliate=t

[Works] Here's quote request /w aff bps set to 0 

https://thornode.ninerealms.com/thorchain/quote/swap?from_asset=BCH~BCH&to_asset=THOR.RUNE&amount=100000000&destination=thor1ukwhpglu7yh2g2rw8h7jvee2r0fv0e90nyxv6v&tolerance_bps=1000&affiliate_bps=5&affiliate=t

**Comment by Orion-9R** [comment]
I've opened an issue in thornode here: https://gitlab.com/thorchain/thornode/-/issues/2038

**Comment by CW-75** [comment]
thanks for your attention. I look forward to the solution

**Comment by CW-75** [comment]
@Orion-9R is possible this affects the following transaction https://runescan.io/tx/C83BC944C4371F9BC97EFF2E4587BF579D83F3FC19F25EF4A441BDC40FCFBA71? . I mean, If you assign manually the affiliate fee on the transaction memo also is throwing an internal error? It couldn't receive a log on the send process from `client.transfer()` function

**Comment by CW-75** [comment]
dupplicated on https://gitlab.com/thorchain/thornode/-/issues/1982
