### ISSUE TITLE
ADD: BIP44 Spec address derivation

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#13]
# Current

Phrase is used directly for entropy

# Desired

BIP 44 compatibility with other wallets. However the client will only use Index 0, but can in future handle multiple indexes at the same time (eg, like using "sub-accounts" in a single wallet). 

## Hardcode SLIP44 path

Hard code in the SLIP44 path into each client as a private variable
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

## Derive key && address using Index 0
`getAddress(): Address`

This should derive using BIP44, but index 0 only. 

# Implementation 

- [x] Bitcoin (`84/0/0/0`)

- [x] Binance Chain  (`44/714/0/0`)

- [x] Ethereum  (`44/30/0/0`)

- [x] THORChain  (`44/931/0/0`)

- [x] Cosmos ( `44/118/0/0`)

**Comment by Thorian1te** [comment]
Closing this issue. nothing heard in a while
