### ISSUE TITLE
[xchain-thorchain] Make getExplorerUrl return url based on network

### ISSUE THREAD

**Issue by AlekseyChepurko** [xchainjs/xchainjs-lib#152]
now return value for ThorChain client's `getExplorerUrl` [is hardcoded.](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain/src/client.ts#L127).
it should be based on current network

**Comment by veado** [comment]
@sarawut11 Pls add an option to change `explorerUrl` (similar to `clientUrl`) by extending parameters of constructor . Something like this:

```ts
constructor({ network = 'testnet', phrase, clientUrl, explorerUrl }: XChainClientParams & ThorchainClientParams {...}

// where 
type ThorchainClientParams = {
  clientUrl?: ClientUrl
  explorerUrl?: ExplorerUrl // similar to ClientUrl
}
```
