### ISSUE TITLE
[xchain-eth]: Export `ETH_DECIMAL`

### ISSUE THREAD

**Issue by veado** [xchainjs/xchainjs-lib#210]
Export [ETH_DECIMAL](https://github.com/xchainjs/xchainjs-lib/blob/f588d54a2fc9e77d51c8f51c3ca1d2710c892005/packages/xchain-ethereum/src/utils.ts#L22) from [index.ts](https://github.com/xchainjs/xchainjs-lib/blob/f588d54a2fc9e77d51c8f51c3ca1d2710c892005/packages/xchain-ethereum/src/index.ts#L3-L10) to make it accessable from outside world

**Comment by junkai121** [comment]
Close by #215
