### ISSUE TITLE
BUG: Class constructor cannot be invoked without 'new' - typescript with commonjs

### ISSUE THREAD

**Issue by drawbit** [xchainjs/xchainjs-lib#230]
The issue happened when trying to deposit tx from @xchainjs/thorchain package.

![image](https://user-images.githubusercontent.com/20286132/108124929-b845d180-7075-11eb-9a27-ab2c1a66f361.png)

Ref: https://stackoverflow.com/questions/50203369/class-constructor-cannot-be-invoked-without-new-typescript-with-commonjs

**Comment by Thorian1te** [comment]
Nothing heard here in a while, closing this issue as it is probably fixed
