### ISSUE TITLE
ADD: Optional Feerate

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#232]
For all the clients

```
client.transfer({amount, recipient, feeRate})
```

make `feeRate` optional, default is "fast". 

- [x] Bitcoin
- [x] Etherem
- [x] Litecoin
- [ ] Bitcoincash

Also, update the client readme to detail this

**Comment by Thorian1te** [comment]
Closing this issue as this has been implemented
