### ISSUE TITLE
ADD: HD Wallet

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#233]
Allow requesting HD Wallet

```
getAddress(index)
```

Index is optional, default 0, if set, the return the address for the index at that level. 

- [x] Bitcoin
- [x] Ethereum
- [x] Binance
- [x] THORChain
- [x] Litecoin
- [x] BitcoinCash

**Comment by davidp94** [comment]
I think we should add it as the instantiation of the `client` optionally as we'd need to sign depending of the index too @thorchain-admin @junkai121

**Comment by mikewyszinski** [comment]
So i've picked up this card and have a few questions, remember i'm new to this project so perhaps I don't have a full picture yet.

1. the original request mentions only getAddress(index), however the current branch also changes the Client constructor to 
```
rootPath?:string
index?:number
```
I'm inclined to back this change out for 2 reasons:

    1. It adds more state to the client libraries when i feel like the less state we manage, the better.
         An example of the tipple effect is that setNetwork() now has to manage [resetting these during a network change(https://github.com/xchainjs/xchainjs-lib/blob/bdcc50346395e9609ee208785e86de20079afeb9/packages/xchain-bitcoin/src/client.ts#L141)
     2.  do we really want consumers of the library need to know the derivations paths or override the derivation paths? I'm inclined to move ALL root paths (including the ledger specific paths )  as constants/ or default configs

2.  seems like setPhrase() returns an address as a convenience, recommend removing this as now we would either needto add an index OR default to index =0 , both of which seem unintuitive for a setter.

**Comment by davidp94** [comment]
> [](https://github.com/xchainjs/xchainjs-lib/blob/bdcc50346395e9609ee208785e86de20079afeb9/packages/xchain-bitcoin/src/client.ts#L141)
> 2. do we really want consumers of the library need to know the derivations paths or override the derivation paths? I'm inclined to move ALL root paths (including the ledger specific paths ) as constants/ or default configs

@veado @thorchain-admin

**Comment by mikewyszinski** [comment]
OK pushing an interim version ...

#  status

-  Bitcoin coded and unit tests passing
-  Litecoin coded and unit tests passing
    - note i think there [ could be a bug in the derivation path](https://github.com/xchainjs/xchainjs-lib/blob/c6fbac36c181aa28ed00c6b83d946846667b5fea/packages/xchain-litecoin/src/utils.ts#L262) **shouldnt the testnet path be  testnet: `m/84'/2'/1'/0` not `m/84'/1'/0'/0` ?**
- Ethereum coded  but unit test refactor imcomplete

still have not started these 
- [  ] BitcoinCash
- [  ] Binance
- [  ] THORChain
- [  ] Cosmos
- [  ] Polkadot

note: tried to push to this branch and got an permdenied

```
ERROR: Permission to xchainjs/xchainjs-lib.git denied to mikewyszinski.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
