### ISSUE TITLE
[xchain-litecoin] sochain api causes CORS issue

### ISSUE THREAD

**Issue by thatStrangeGuyThorchain** [xchainjs/xchainjs-lib#246]
sochain api does not provide appropriate Access-Control-Allow-Origin  at the send_tx  endpoint

![image](https://user-images.githubusercontent.com/67793194/108713078-c50c6e80-7528-11eb-86bb-432fbc7547f9.png)

need to replace it to use acceptable api

**Comment by junkai121** [comment]
We are using our own node proxy - https://testnet.ltc.thorchain.info
