### ISSUE TITLE
Add `pre-commit` hook to lint packages

### ISSUE THREAD

**Issue by veado** [xchainjs/xchainjs-lib#25]
by using [husky](https://www.npmjs.com/package/husky) / [lint-staged](https://www.npmjs.com/package/lint-staged)

**Comment by HelloKashif** [comment]
> by using [husky](https://www.npmjs.com/package/husky) / [lint-staged](https://www.npmjs.com/package/lint-staged)

Done 
![image](https://user-images.githubusercontent.com/9801383/97525196-a1597180-19e9-11eb-9bce-67215f3d8cb2.png)
