### ISSUE TITLE
Move independent methods as utils for each client

### ISSUE THREAD

**Issue by thatStrangeGuyThorchain** [xchainjs/xchainjs-lib#287]
for example [getExplorerTxUrl](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain/src/client.ts#L270) is independent by `phrase` method and there should be a possibility to use directly without a client itself.

As possible solution to avoid any backward compatibility issues there is a sense to move all independent methods to the `utils.ts` file and make client to use them without changing client's API

**Comment by Thorian1te** [comment]
Closing this issue as this has been implemented
