### ISSUE TITLE
Missing dependancies for @xchainjs/xchain-bitcoincash

### ISSUE THREAD

**Issue by nshCore** [xchainjs/xchainjs-lib#293]
Then using this package I had to manually install

@psf/bitcoincashjs-lib
bchaddrjs

As these modules where not found

they should be probably be moved to dependancies rather than dev dependancies, or requiring them to be installed as peerDependancies.

**Comment by davidp94** [comment]
> Then using this package I had to manually install
> 
> @psf/bitcoincashjs-lib
> bchaddrjs
> 
> As these modules where not found
> 
> they should be probably be moved to dependancies rather than dev dependancies, or requiring them to be installed as peerDependancies.

https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-bitcoincash/package.json#L48
https://github.com/xchainjs/xchainjs-lib/tree/master/packages/xchain-bitcoincash#installation
