### ISSUE TITLE
ADD: FeeRates from thorchain

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#299]
# Thirdparty services are delayed

Instead of using third-parties, default to use thorchain gas oracle instead, which is always up to date

https://thornode.thorchain.info/thorchain/inbound_addresses

Gas rates you can get for each chain, if nothing there, then use the other service providers.

fastest: 1.5x 
fast: 1x
average: 0.67x

For PoW chains, the gas rate is a feeRate. 
For BNB, it is fixed (and not really relevant) but it is the total fee to pay

**Comment by mikewyszinski** [comment]
reviewed this yesterday.  I propose the following approach:

1.  create a base class in xchain-client `XChainBase` and create  getFeesFromThorchain() there
    1. this would also allow us to centralize the setPhrase() and purgeclient() logic in this class helping ensure more consistent behavior across chain implementations
 2. refactor all existing client implementation to call super.getFeesFromThorchain() and if no response after x sec timeout(default 3? secs) then it falls back to fetchign for the explorer or alternate source.

**Comment by mikewyszinski** [comment]
going to proceed as described in the comment above.

**Comment by mikewyszinski** [comment]
@veado @thorchain-admin @stuartwk  i just pushed the initial implementation for this, it adds a base class BaseXChainClient to centralize the fetching of the gas prices (and it also centralizes some  other common attributes)  

i refactored the xchain-bitcoin client to extend this base class, it was a pretty clean change and removed a bunch of redundant  code
