### ISSUE TITLE
ADD: SPEED UP and CANCEL

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#300]
# Need to allow xchainjs to facilitate handling pending tx

## CANCEL
Need to find the pending UTXOs or pending NONCE and spend back to SELF

## SPEED UP
Need to find the pending UTXOs or pending NONCE and redo the desired tx. 

# Implementation - CANCEL

`cancel()` should:
1) if UTXO, then find the pending UTXOs and re-consume them back to self
2) if Account, then find the latest nonce and re-spend back to self

# Implementation - SPEED UP

`bump(txData)` should:
1) if UTXO, then find the pending UTXOs and re-consume them with new txData
2) if Account, then find the latest nonce and re-spend back with new txData

**Comment by Thorian1te** [comment]
Closing this issue as nothing has been heard here in a year
