### ISSUE TITLE
ADD: validateAddress in the xchain-client

### ISSUE THREAD

**Issue by skyorion427** [xchainjs/xchainjs-lib#302]
Address validation is required for sending assets to the correct address.

Currently, only binance SDK has a validation but it would be nice to have validation for all chains.

For BTC: https://www.npmjs.com/package/bitcoin-address-validation

**Comment by veado** [comment]
> Address validation is required for sending assets to the correct address.

All `xchain-*` packages have already a `validateAddress` helper, any UI can already use these before sending any tx: https://github.com/xchainjs/xchainjs-lib/search?l=TypeScript&q=validateAddress

**Comment by skyorion427** [comment]
thanks for letting me know.
