### ISSUE TITLE
Axios is using an incorrect adapter in a node environment

### ISSUE THREAD

**Issue by Georift** [xchainjs/xchainjs-lib#319]
When the packages are built rollup is configured with `browser: true` which picks a browser only axios build.

Notice how xhr has been selected for both environment in this statement:

```typescript
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = xhr;
  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = xhr;
  }
  return adapter;
}
```

I've only run into this problem in `@xchainjs/xchain-litecoin` although I believe this should be a similar problem in any package that are using axios. `@xchainjs/xchain-binace` doesn't seem to have this issue as it's using another package under the hood as a client.

axios has been listed as a peer dependency, could we remove it from the rollup bundle?

**Comment by mikewyszinski** [comment]
this is fixed  in PR #362 along with another node compatibility change. changes have been published to NPM, please pull the latest ;-)
