### ISSUE TITLE
ADD: use crypto-js instead of node's crypto to support mobile development such as react-native

### ISSUE THREAD

**Issue by severinwullschleger** [xchainjs/xchainjs-lib#331]
xchain-crypto and some other packages are using the crypto package from node. To make xchainjs also usable for react native I suggest using crypto-js instead of crypto.

**Comment by mikewyszinski** [comment]
@severinwullschleger any chance you can point to a public repo that demonstrates the error? we just refactored a few things to better support running in nodejs, would like to include react-natove but want to better understand the issue

**Comment by severinwullschleger** [comment]
Hi @mikewyszinski 

For react-native it is suboptimal when node packages like "crypto" are used. If xchainjs should be cross platform one should focus on not using the sub-packages of node. instead we should use packages like crypto-js which do not require node. I realized that it is a relativally big task to do so. Therefore not sure if it makes sense to do that now.

@JonnyBurger do you have something to add here?

we were now able to use xchainjs on react native with a few patches and resolver adjustments. See here https://github.com/THORWallet/thorwallet-react-native/blob/master/metro.config.js
