### ISSUE TITLE
ADD: BCH legacy address validation

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#335]
# current

* BCH legacy addresses are interpreted as invalid and not allowed to send to
* Users need to use services like https://tools.bitcoin.com/cash-address-converter/ to convert

# Desired
* convert all BCH addresses to cashAddr
* to a validation check *after* converting
* send always to cashAddre (ie, convert before sending)

Use this method here:
https://github.com/jbdtky/bitcoincashjs/blob/master/src/address.js#L348

Or just import and use:

```
const bch = require('bitcoincashjs');

const Address = bch.Address;
const CashAddrFormat = Address.CashAddrFormat;

const address = new Address('1MF7A5H2nHYYJMieouip2SkZiFZMBKqSZe');

console.log(address.toString()) // 1MF7A5H2nHYYJMieouip2SkZiFZMBKqSZe
console.log(address.toString(CashAddrFormat)) // bitcoincash:qr0q67nsn66cf3klfufttr0vuswh3w5nt5jqpp20t9
```

**Comment by mikewyszinski** [comment]
@thorchain-admin  so i have a possible fix but i actually can't reproduce a validation failurte using legacy addresses...

shouldn't this recipient trigger a failure? 
```
const txId = await bchClient.transfer({
      walletIndex: 0,
      recipient: 'muLqdHvyvbbB9oz4xnWotEuGVVeJtQZQxx',
      amount: baseAmount(100, BCH_DECIMAL),
      feeRate: 1,
    })
```

**Comment by mikewyszinski** [comment]
@thorchain-admin @veado @davidp94 this one is ready to merge once someone gives it the once over
