### ISSUE TITLE
[BUG] dust error tx when accumulating memo output with 0 value

### ISSUE THREAD

**Issue by thorswapdev** [xchainjs/xchainjs-lib#336]
## Issue Description

when adding a memo with `0 value` to `outputs` using `coinselect/accumulative` , psbt composite doesn't work properly,
resulting `dust` error when broadcasting the raw tx.

## Solution

- don't add memo output using `coinselect/accumulative`.
- add memo using `psbt.addOutput` separately.

**Comment by thorswapdev** [comment]
@mikewyszinski , we faced the same issue for ledger integration and solved by using `psbt.addOutput` instead.

let me know your thoughts

**Comment by mikewyszinski** [comment]
goign to modify the fix to avoid undercalculating fees if a memo is present
