### ISSUE TITLE
ADD: Master Readme improvements

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#360]
# Current

The master readme is light on docs/examples. The instructions are in the `/package/<client>/readme` but not obvious for new users

# Desired

Have a very enticing master readme:
* install instructions
* Simple overview
* Various examples and walkthroughs (for any client, any function)
* With links that point deeper into packages
* Pretty pictures and logos and emojis

Good example:
https://github.com/cosmostation/cosmosjs

**Comment by Thorian1te** [comment]
Closingthis issue as it has been completed
