### ISSUE TITLE
BIP32 Paths do not conform to standards

### ISSUE THREAD

**Issue by mperklin** [xchainjs/xchainjs-lib#364]
### Summary
The BIP32 paths used in this project do not conform to globally-accepted standards. 

### Impact
Users will not find their coins when moving mnemonics to/from xchainjs. 
* Users who create their mnemonic on xchainjs and move it to another wallet will not see their transaction history
* Users who take an existing mnemonic with transaction history and move it into xchainjs will not see their transaction history

### Solution
Fix all paths to conform to BIP44/84 standards so that mnemonics created/imported by xchainjs are compatible with other wallets.

Examples:
https://github.com/xchainjs/xchainjs-lib/blob/570a2186fc10d633886f2a0ddb7e0b20d295bcad/packages/xchain-polkadot/src/client.ts#L53
* The `44` ordinal should be hardened: `44'`
* The `coin_type` ordinal should be hardened with a `'` too
* The account `0` should be hardened with `0'`
* The last key index is hardened when it should not be

**Comment by maikelmclauflin** [comment]
if i recall correctly, polkadot does use `//` to denote hardened for their custom uri parser

and as far as the last key, i think that's a requirement of the uri parser. fails otherwise

**Comment by mikewyszinski** [comment]
i'm going to propose we address this by making xhchainjs have a pluggable derivation path, something along the lines of:

## pseudo code
```
import { DerivationPath, BTCClient } from  ' xchain-client'

// create a btc client tha uses default HD paths
const btcClient = new BTCClient({
phrase: ' blah blah blah'
network: 'testnet',
DerivationPath: DerivationPath.XCHAIN_DEFAULT
})

// create a btc client tha uses  HD paths that are identical to Ledger v1
const btcClient = new BTCClient({
phrase: ' blah blah blah'
network: 'testnet',
DerivationPath: DerivationPath.LEDGER_V1
})

// create a btc client tha uses  HD paths that are identical to keepkey v1
const btcClient = new BTCClient({
phrase: ' blah blah blah'
network: 'testnet',
DerivationPath: DerivationPath.KEEPKEY
})

// create a btc client tha uses  HD paths that are identical to xchain v1.0
const btcClient = new BTCClient({
phrase: ' blah blah blah'
network: 'testnet',
DerivationPath: DerivationPath.XCHAIN_V1
})

// create a btc client tha uses  HD paths that are identical to what jaxx uses
const btcClient = new BTCClient({
phrase: ' blah blah blah'
network: 'testnet',
DerivationPath: DerivationPath.JAXX
})
```

i think this gives us the needed flexibility to support being compatible with other wallet providers so users of the lib can easily pick from a bunch of precanned HD paths or optionally create a custom one

also propose this goes into the @next version

thoughts?

**Comment by mikewyszinski** [comment]
closing as polkdot is no longer supported, we can revisit again if it is
