### ISSUE TITLE
Move assets declarations from xchain-util to each packages.

### ISSUE THREAD

**Issue by jgo121** [xchainjs/xchainjs-lib#38]
Move assets declarations from xchain-util to each packages.

such as AssetBNB, AssetBTC, AssetETH, ...

![image](https://user-images.githubusercontent.com/39806640/97007632-0b56be80-1585-11eb-8bb7-6db41492bcd0.png)
![image](https://user-images.githubusercontent.com/39806640/97007652-101b7280-1585-11eb-9547-55af9291514e.png)

**Comment by Thorian1te** [comment]
closing this issue, Asset declarations are working fine in xchain-util
