### ISSUE TITLE
BUG: thorchain client doesn't return the tx id in network timeout situation 

### ISSUE THREAD

**Issue by mikewyszinski** [xchainjs/xchainjs-lib#387]
In the thorchain client, after the transaction has been submitted it checks whether the transaction is included in the block. When the network has a high latency, as the testnet has right now, an  timeout error gets thrown and the transaction hash is not returned. 
The transaction is still successfully submitted and executed, but there is no way to track the transaction due to the missing hash. 

Strangely all consecutive transactions which include identical assets as the preceding "failing" transaction, return the transaction hash and don't throw any error. Those deposits only take a fraction of time, indicating an anomaly. The transactions are never included in a block, which I think has to do with the wrong sequence number the wallet injects in the tx.

reported by @DollyVolley in telegram channel - https://t.me/xchainjs/2304

**Comment by veado** [comment]
> reported by @DollyVolley in telegram channel

@mikewyszinski Could you add a link to the discussion at Telegram, pls ;)

**Comment by DollyVolley** [comment]
Sorry @veado I also missed that comment!
The link is already in the description, but here once again: https://t.me/xchainjs/2304
