### ISSUE TITLE
ADD: Dogecoin

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#396]
Some libraries to wrap

https://github.com/cryptocoinjs/coinkey/blob/master/test/coinkey.test.js
https://github.com/bitpay/bitcore/tree/master/packages/bitcore-lib-doge

Some APIs to choose from (for balance/post-tx)

https://sochain.com/doge

**Comment by mikewyszinski** [comment]
started this effort, published an initial commit
