### ISSUE TITLE
[xchain-cosmos] Update cosmos-client to latest version (0.42.14)

### ISSUE THREAD

**Issue by hinterlist** [xchainjs/xchainjs-lib#398]
The `cosmos-client` used in the package is a bit outdated and need to be updated to latest version which hash breaking changes and not compatible with current `xchain-cosmos`.

**Comment by veado** [comment]
@dimitrykislichenko Are you able to fix it?

_Side note:_ An update to latest `cosmos-client` will break `xchain-thorchain` and need to be fixed there as well.

**Comment by mikewyszinski** [comment]
this is ending up being much more invasivethat expected.  i'm going to roll back to a compatible version with our code until we can make these changes.

**Comment by veado** [comment]
Pls update other dependencies as well.

ncu :eyes:  https://www.npmjs.com/package/npm-check-updates

(status 01-09-2021)

```ts
ncu
Checking xchainjs-lib/packages/xchain-cosmos/package.json
[====================] 6/6 100%

 @xchainjs/xchain-client  ^0.10.1  →  ^0.10.2     
 @xchainjs/xchain-crypto   ^0.2.4  →   ^0.2.5     
 @xchainjs/xchain-util     ^0.3.0  →   ^0.3.1     
 axios                    ^0.21.0  →  ^0.21.1     
 cosmos-client             0.39.2  →  0.42.14     
 nock                     ^13.0.5  →  ^13.1.3     
```

**Comment by mikewyszinski** [comment]
closed by [another issue](https://github.com/xchainjs/xchainjs-lib/pull/436)
