### ISSUE TITLE
BUG: I have my interface blocked due to the fact that clients initialization takes long and contains network sync requests.

### ISSUE THREAD

**Issue by NikitosGolubev** [xchainjs/xchainjs-lib#401]
Well, hello guys. Me and my company developing product which utilizes your library and we have an issue.

Consider this code samples:
```
 new BTCClient({
      network: this.config.networkType,
      phrase: this.config.phrase,
      sochainUrl: SOCHAIN_URL,
      blockstreamUrl: BLOCK_STREAM_URL,
    });
```

```
new BNBClient({
      network: this.config.networkType,
      phrase: this.config.phrase,
});
```
We are utilizing almost all of your clients in web. (thorchain, bitcon, binance and etc).

And there are two major problems for us related to **getAddress()** method in your clients.

I've explored your source code and I figured out that you dispatch method **this.setPhrase()** at BaseXChainClient constructor. This method calls **this.getAddress()** method which is abstract.  And it turns out, that each client which implements this kind of method does perform some kind of network request.

**PROBLEM**: *When I initialize up to 6 clients, they perform 6 requests and this requests turns out to be synchronous which eventually freezes user interface for 16-20 **SECONDS**. And this waiting time really hurts User Experience as entire page gets blocked.*

**PROBLEM №2**: *Because **getAddress()** seems to be synchronous, each time I need to call this function, my users have to face with same freezing effect. Because of that I'm forced to collect getAddress on the initial wallet instantiation and basically cache it. BUT: Considering you guys dispatch **getAddress()** at **this.setPhrase()**, can we maybe store the returned address in the prop let's say **cachedAddress**? That would have been very handy because I would have been free from dispatching external requests just to collect addresses at my client code.*

**FEATURE REQUEST**: Please make getAddress asynchronous if it's possible. If it's not possible, please store the address you fetch in constructor at some public readonly property on the instance.

Thank you!

**Comment by NikitosGolubev** [comment]
We collaborated with developer. There're no sync network requests involved. That's just browsers being slow(less powerful than node.js environment) at generating addresses.

**Comment by mikewyszinski** [comment]
we will avoid callig getAddress() during the BaseXChainClient constructor, since this value is not returned, it's completely useless.
