### ISSUE TITLE
[xchain-binance] `public_key` of `Account` can be `null`

### ISSUE THREAD

**Issue by veado** [xchainjs/xchainjs-lib#441]
## Issue

- `getAccount` might be fail for Ledger addresses

## Example (random `Ledger` address): https://testnet-dex.binance.org/api/v1/account/ returns `public_key: null`

```ts
{
  "account_number": 36990,
  "address": "tbnb...0skj",
  "balances": [
    {
      "free": "0.66927332",
      "frozen": "0.00000000",
      "locked": "0.00000000",
      "symbol": "BNB"
    }
  ],
  "flags": 0,
  "public_key": null,
  "sequence": 0
}

```

## TODO

- Fix `isAccount` guard

**Comment by YumKimilMaya** [comment]
Is the issue still happenning with the newer binance API ??
