### ISSUE TITLE
[xchain-thorchain] How to differentiate between which `from` txn is fees vs actual value?

### ISSUE THREAD

**Issue by loxator** [xchainjs/xchainjs-lib#445]
Hi, I am seeing in API response while getting transactions for Thorchain that it sometimes has 2 `from / to` values and sometimes just 1. There's no information which says which is the `valueSent` vs `fees`. Does anyone have any idea? Thanks!

![image](https://user-images.githubusercontent.com/18169190/135932286-48143d7d-2679-4d41-b43a-a74395a14095.png)

However in outgoing requests, I can see the [node](https://thornode.thorchain.info/txs/BD5B5448D70D6802189FF219C77655AB7E74A71C4686925B58CA879556E34D8C) replies with much more detailed data. Fees has its own object and value has its own, don't understand where its being transformed.

From what I have gathered, if there are 2 objects in the `Txfrom[]`, then the first one is fees and second one is the actual value sent. However, this is just a hunch so need to be sure.

Any help is appreciated.

**Comment by YumKimilMaya** [comment]
Maybe if you compare the "amount" to the actual amount you were supossed to send or receive
