### ISSUE TITLE
ADD: Stagenet Support

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#455]
- [ ] For `xchain-thorchain` create new `stagenet` init variable, which loads `stagenet.thornode.ninerealms.capital` as baseURL for posting tx. 
- [ ] All other chains do not need stagenet support

**Comment by polaris-9r** [comment]
I have some changes that I'd like to push to a remote branch for this. Is there any way I can get push access to open a PR? Thanks!

**Comment by veado** [comment]
Resolved by #456
