### ISSUE TITLE
[Bug] No proper check in buildTX

### ISSUE THREAD

**Issue by 0xNegnin** [xchainjs/xchainjs-lib#507]
xchainjs-bitcoin/utils buildTX needs to check that the amount sent + fee cannot exceed the users balance, if it does then the amount sent must be equal to the users balance - fee, it should not throw an error but instead determine the new implicated amount to send (as it is maximum in this context).

**Comment by mikewyszinski** [comment]
@0xNegnin sorry about the long delay, looking at this now...

under the covers, we are using https://github.com/bitcoinjs/coinselect/blob/master/accumulative.js to select the inputs  based on the desired outputs in the tx. if not it will error out. 

I think sending the entire balance in this case is not a good idea as that's not what the caller requested. 

Could a workaround be the following?

1. make your call to transfer()  
2. if it throws Error('Insufficient Balance for transaction')
3. you catch, check balances and possibly resubmit if it makes sense?
