### ISSUE TITLE
ADD: All clients to have deposit() function

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#540]
# Overview
Allow all clients to `deposit()` into THORChain to make a swap, add liquidity or more. 

**Checklist**
- [ ] BTC
- [ ] BCH
- [ ] LTC
- [ ] DOGE
- [ ] BNB
- [ ] TERRA
- [ ] ETH

# Implementation

## Utils
* add a new func in `-utils`:
```
getInboundDetails(chain) => 
{"vault":"address"; 
?"router":"address"; 
"haltedChain":bool; 
"haltedTrading":bool;
"haltedLP":bool`}
```
Use:
Primary
https://midgard.ninerealms.com/v2/thorchain/inbound_addresses
https://midgard.ninerealms.com/v2/thorchain/mimir
backup
https://midgard.thorswap.net/v2/thorchain/inbound_addresses
https://midgard.thorswap.net/v2/thorchain/mimir

to return the correct details for the chain (catch errors)

## UTXO, BFT chains
Bitcoin, Litecoin, Doge, Bitcoincash, Terra, BNB
Return error if haltedChain, haltedTrading
```
params: walletIndex, asset, amount, memo
.deposit(params){
   let vault = utils.getInboundAddress(chain)
  let hash = client.transfer(vault, params)
  return hash
}
```

## EVM chains
Ethereum
Return error if haltedChain, haltedTrading
```
params: walletIndex, asset, amount, memo
.deposit(params){
   let vault = utils.getInboundAddress(chain) -> goes into depositParams
   let router = getInboundRouter(chain)
   let hash = client.call(index, router, routerABI, deposit, depositParams)
  return hash
}
```
Put the `routerABI.json` into the `src/data` folder and load
https://api.etherscan.io/api?module=contract&action=getabi&address=0x3624525075b88B24ecc29CE226b0CEc1fFcB6976

Similiar to the .approve() function
https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-ethereum/src/client.ts#L562

## THOR chains
Already done: 
https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain/src/client.ts#L426

**Comment by osabl** [comment]
Pull request https://github.com/xchainjs/xchainjs-lib/pull/551
