### ISSUE TITLE
FIX: -ethereum Hide balances below 4 sigfig

### ISSUE THREAD

**Issue by thorchain-admin** [xchainjs/xchainjs-lib#541]
Add a check in `getBalance()` to hide dust balances 

eg <0.0001 is hidden

**Comment by mikewyszinski** [comment]
this was quick to do, but feels like the caller could easily filter any balances they do not want to see themselves, no?

**Comment by veado** [comment]
> this was quick to do, but feels like the caller could easily filter any balances they do not want to see themselves, no?
> 
> not sure this change is needed..

Agree. Let wallet devs add this feature in its wallet code if needed - but not in xchain-ethereum.

**Comment by mikewyszinski** [comment]
ok going to close this without merging, if any caller feels the need to implement this it can be done as follows:

```
export const MIN_TOKEN_AMOUNT_TO_LIST = baseAmount(0.0001, ETH_DECIMAL)
balances.filter((balance) => balance.amount.gt(MIN_TOKEN_AMOUNT_TO_LIST))
```
