### ISSUE TITLE
create xchain-midgard module

### ISSUE THREAD

**Issue by mikewyszinski** [xchainjs/xchainjs-lib#569]
create a new new module called xchain-midgard that exposes all midgard api functions defined the the swagger  doc

ref: https://midgard.thorchain.info/v2/swagger.json

we should create this lib the same was asgardex does it, by autogenerating the client code using openapi-generator-cli : https://github.com/thorchain/asgardex-electron/blob/develop/package.json#L25

**Comment by Orion-9R** [comment]
As new Midgard versions are released, we need a plan on how to maintain the generated client.

**Comment by Thorian1te** [comment]
I had a think about this. The easiest way is to just manually create a branch and re-generate the cli, test and then publish. I suppose some kind of build pipeline could work that is triggered by an updated Midgard version number.
