### ISSUE TITLE
FIX: gaslimit estimate for withdrawl underestimates the gas by 29x

### ISSUE THREAD

**Issue by mikewyszinski** [xchainjs/xchainjs-lib#574]
discord conversation: https://discord.com/channels/838986635756044328/974028719435952208

Fix: in deposit() 
```
check to see if there is a memo defined,
if there is a memo  
      if memo is type  withdrawal
          use a gas mutliplier = 50
      else 
         use default gas multiplier
```

**Comment by veado** [comment]
@mikewyszinski Don't use another hardcoded multiplier - this value needs to be changed over time as well, similar to hardcoded gas limit we had in xchain-thorchain before. See ongoing discussion at Discord https://discord.com/channels/838986635756044328/974028719435952208/974263213543788544
