### ISSUE TITLE
xchain-binance getTransactions issues

### ISSUE THREAD

**Issue by cryptotester** [xchainjs/xchainjs-lib#575]
http://docs.xchainjs.org/xchain-client/xchain-binance/available-functions/client.html

getTransactions

Get transaction history of a given address with pagination options. By default it will return the transaction history of the current wallet.

**Issue 1**: by default -I just tested it- it doesn't give my wallet transactions, it gives all transactions. So `address` must be specified in the params.

**Issue 2**: There already several details except the amount. This is a bummer because like this one needs to call for each transaction the getTransactionData method.

I tried (for each transaction) to call `getTransactionData(trxHash` and I got:

```
 data: { message: 'API rate limit exceeded' }
```

Sometimes I get api rate limit exceeded also if I call getTransactions just one time. E.g. last time I called it was a few minues ago, I call it again and get:

```
    data: { message: 'API rate limit exceeded' }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  level: 'error',
  timestamp: '2022-05-15T07:57:38.194Z',
  [Symbol(level)]: 'error',
  [Symbol(message)]: '2022-05-15T07:57:38.194Z: Request failed with status code 429'
}
```

What kind of API is it used? Is it possible for a user to register and get a higher limit or so?

Thank you.

**Comment by mikewyszinski** [comment]
@cryptotester thanks for raising this!


1.  yes seems you are correct, it does not default to the address of the wallet. after checking a couple other libraries (btc,bch,eth) none of them seem to default to the current address. i think defaulting to current address is a bad idea since the phrase is optional so there may not be an address. 
    I'll create a PR with the following:
    1. for all libraries, make address mandatory param
    2. fix all docs to reflect address is required 
2.  current endpoint we use --> https://dex.binance.org/api/v1/transactions , rate is 5 req/min
     it does not look like there is any way to procure a key for a higher throughput, however there is a different endpoint avail able that has a default rate of 500 req/5 min --> https://docs.binance.org/api-reference/dex-api/block-service.html#apiv1txs 
also seems like there are multiple API urls availble to hit instead of just one API url . 
    I'll create a PR to do the following:
    1. migrate to new endpoints
    3. change constructor to allow the input of an API URL, that way client can have multiple instances to spread load
    4.  add the amount to the tx results (looks like its there) 

@veado any concerns with the above?

**Comment by veado** [comment]
@mikewyszinski Sounds like a good plan!

**Comment by cryptotester** [comment]
> @cryptotester thanks for raising this!
> 
> 1. yes seems you are correct, it does not default to the address of the wallet. after checking a couple other libraries (btc,bch,eth) none of them seem to default to the current address. i think defaulting to current address is a bad idea since the phrase is optional so there may not be an address.
>    I'll create a PR with the following:
>    
>    1. for all libraries, make address mandatory param
>    2. fix all docs to reflect address is required
> 2. current endpoint we use --> https://dex.binance.org/api/v1/transactions , rate is 5 req/min
>    it does not look like there is any way to procure a key for a higher throughput, however there is a different endpoint avail able that has a default rate of 500 req/5 min --> https://docs.binance.org/api-reference/dex-api/block-service.html#apiv1txs
>    also seems like there are multiple API urls availble to hit instead of just one API url .
>    I'll create a PR to do the following:
>    
>    1. migrate to new endpoints
>    2. change constructor to allow the input of an API URL, that way client can have multiple instances to spread load
>    3. add the amount to the tx results (looks like its there)
> 
> @veado any concerns with the above?

Thx Mike, if you are on the piece and wanna check some of your swaps maybe between thorchain and binance chain, you can also have a look at #584 that I just reported, also having some issues. I think (and hope) this one may even easier to fix.

THX ;)

**Comment by hippocampus-web3** [comment]
Hi! @mikewyszinski @veado some news about this?
