### ISSUE TITLE
xchain-thorchain getTransactions by synth

### ISSUE THREAD

**Issue by ArtiomTanshyn** [xchainjs/xchainjs-lib#595]
I am sending a synthetic asset. To see the transactions of this synthetic asset, I use getTransactions. However, the data I am getting has the correct hash, but not the correct asset.

For example: I sent DOGE synth, and in the transaction I receive the asset:
{chain: "THOR"
symbol: "RUNE"
synth: false
ticker: "RUNE"}

Thus, it turns out that my transactions show the commission of this transfer. But the hash shows the correct data.
<img width="317" alt="Снимок экрана 2022-06-10 в 00 01 51" src="https://user-images.githubusercontent.com/59205632/172943893-244001dd-4c21-4847-b434-d08e1a1899e4.png">

I expect to receive an asset with DOGE data.

**Comment by mikewyszinski** [comment]
do you have a snippet of code that you can add so i can review?

**Comment by ArtiomTanshyn** [comment]
Yes. I send 0.03 synth doge.

When I get transaction:

async getThorTxs () {
      const txs = await WorkerService.getTransactions('thorchain', {
        address: 'thor1puhn8fclwvmmzh7uj7546wnxz5h3zar8adtqp3'
      })
      console.log(txs)
    },

Console showed me:
date: Fri Jun 10 2022 11:24:43 
direction: "OUT"
fromAddr: "thor1puhn8fclwvmmzh7uj7546wnxz5h3zar8adtqp3"
toAddr: "thor1dheycdevq39qlkxs2a6wuuzyn4aqxhve4qxtxt"
txAsset: "RUNE"
txBlockchain: "thorchain"
txHash: "1260FC952CEA30A46BFC6D54DE808675B787046A7BB8FC559D1EB62F64B06D13"
txType: "transfer"
unconfirmed: false
value: 0.02

But txAsset must be DOGE, and value must be 0.03.
The transaction hash is correct: https://viewblock.io/thorchain/tx/1260FC952CEA30A46BFC6D54DE808675B787046A7BB8FC559D1EB62F64B06D13
