### ISSUE TITLE
Remove Network enum from README

### ISSUE THREAD

**Issue by HelloKashif** [xchainjs/xchainjs-lib#6]
Enums were removed in favor of strings for "Network" type

Need to updated README
https://github.com/Pusher-Labs/asgardex-clients/tree/master/packages/asgardex-client#set-network

**Comment by veado** [comment]
enum is back :arrow_down: 
```ts
export enum Network {
  Mainnet = 'mainnet',
  Testnet = 'testnet',
}
```

^ https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-client/src/types.ts#L5-L8
