### ISSUE TITLE
LTC Request failed with status code 500

### ISSUE THREAD

**Issue by Haessler16** [xchainjs/xchainjs-lib#612]
hello, i have this issues when i am trying to do a swap in mainnet:

**Request failed with status code 500**

my dependencies versions are as follow:

@xchainjs/xchain-client: 0.11.3
@xchainjs/xchain-crypto: 0.2.6
@xchainjs/xchain-util: 0.7.1
 bitcoinjs-lib: 6.0.1
 coininfo: 5.2.1
 wif: 2.0.6

**Comment by Thorian1te** [comment]
Hey @Haessler16 is this issue to relevant with package thorchain-amm released? 
1. Was there an outcome or are you still stuck?

**Comment by Haessler16** [comment]
Hello @Thorian1te thank you for replying. 

Yes, we were able to fix this issue, the problem was in the memo. We were using a thor address in the affiliate fee in our memo, but when we changed the thor adress to a ThorName, the error disappeared.
