### ISSUE TITLE
Xchain testnet provider issue at integration

### ISSUE THREAD

**Issue by blockchain-app12** [xchainjs/xchainjs-lib#625]
Hi Team,
I tried this sample 
// import `xchain-thorchain`
import { Client } from '@xchainjs/xchain-thorchain'

// Create a `Client`
const client = new Client({ network: 'testnet', phrase: 'my secret phrase' })

// get address
const address = client.getAddress()
console.log('address:', client.getAddress()) // address: tthor13gym97tmw3axj3hpewdggy2cr288d3qffr8skg

// get balances
const balances = await client.getBalance(address)
console.log('balances:', balances[0].amount.amount().toString()) // balance: 6968080395099

// get transactions
const txs = await client.getTransactions({ address })
console.log('txs total:', txs.total) // txs total: 100

// get transaction details
const tx = await client.getTransactionData('any-tx-hash', address)
console.log('tx asset:', tx.asset) // tx asset: { chain: 'THOR', symbol: 'RUNE', ticker: 'RUNE' }

Here By I attached the error response 
![image(1)](https://user-images.githubusercontent.com/48212011/184329381-448bbe22-74fe-46fb-b2b1-e2d43d8e3738.png)

kindly let me know the integrating the xchain-thorchain.kindly provide the support

**Comment by mikewyszinski** [comment]
hi 

replace 

`const client = new Client({ network: 'testnet', phrase: 'my secret phrase' })
`
with 
`
const chainIds = {
  [Network.Mainnet]: 'thorchain-mainnet-v1',
  [Network.Stagenet]: 'chain-id-stagenet',
  [Network.Testnet]: 'thorchain-testnet-v2',
}
const client = new Client({ network: 'testnet', phrase: 'my secret phrase',chainIds })
`
you can refer to the docs for a more fiull explanation --> http://docs.xchainjs.org/xchain-client/xchain-thorchain/how-to-use.html

**Comment by hippocampus-web3** [comment]
@Thorian1te this issue has been inactive for almost a year, can we close it? Maybe we should set up a bot to close bugs that have been inactive for such a long time.
