### ISSUE TITLE
I need help with the below error.

### ISSUE THREAD

**Issue by bohyun-korbit** [xchainjs/xchainjs-lib#633]
Transaction sent: {}
(node:36641) UnhandledPromiseRejectionWarning: Error: Error broadcasting: signature verification failed; please verify account number (53298) and chain-id (thorchain-mainnet-v1): unauthorized

thorchain-rune coin

**Comment by Thorian1te** [comment]
Please make sure your phrase is correct, that is a cryptographic related error when intitializing the client.
