### ISSUE TITLE
signature verification failed 

### ISSUE THREAD

**Issue by sera-korbit** [xchainjs/xchainjs-lib#634]
Hi!

I have problem with broadcasting Tx, using **@xchainjs/xchain-thorchain**.
When I broadcasted transaction to node URL, I got error **_" signature verification failed; please verify account number and chian-id(thorchain-mainnet-v1) : unauthorized"_**
Is there any proper way to solve this? Or what is the exact cause of this?

please check ASAP.

thanky you

**Comment by Thorian1te** [comment]
Please make sure your phrase is correct, that is a cryptographic related error when intitializing the client.

**Comment by sera-korbit** [comment]
Hi
I found that transfer() method is wrong while adding signature in TxBuilder.

**Comment by Thorian1te** [comment]
Make sure your `xchain-thorchain` is the right version number. It appears to be already fixed.
