### ISSUE TITLE
LTC transfer only returns 405 and 503 status codes

### ISSUE THREAD

**Issue by resera** [xchainjs/xchainjs-lib#646]
Recently, the LTC transfer method started returning 405 (Bad Method) and 503 (Service Not Available) status codes. Requests fail all the time. Any idea what might be the problem?

**Comment by mikewyszinski** [comment]
we noticed this as well, seems to be one or more of the online providers DOGE seems to be affected as well ....looking into the possible fixes

**Comment by mikewyszinski** [comment]
@resera we released an updated ltc/btc client, can you let us know if you are still getting any issues?

**Comment by resera** [comment]
> @resera we released an updated ltc/btc client, can you let us know if you are still getting any issues?

I manually changed LTC node URL, and it resolved the issue.
