### ISSUE TITLE
Update `Fees`

### ISSUE THREAD

**Issue by veado** [xchainjs/xchainjs-lib#65]
Make values for  `fast` and `fastest` necessary (not optional). If there is any chain, which provides one fee only, we will set same value for `average`, `fast`, `fastest`.

### HAVE

```ts
export type Fees = {
  type: FeeType
  fastest?: BaseAmount
  fast?: BaseAmount
  average: BaseAmount
}
```

### WANT

```ts
type Fees = {
    type: FeeType
    fastest: BaseAmount
    fast: BaseAmount
    average: BaseAmount
}
```

**Comment by thatStrangeGuyThorchain** [comment]
@veado what is expected when there is no options for fee ? just return everywhere the same value ?

**Comment by veado** [comment]
> If there is any chain, which provides one fee only, we will set same value for average, fast, fastest.

@thatStrangeGuyThorchain  Yes ^
