### ISSUE TITLE
Why does getTransactionData always return `RUNE` as the asset in getTransactionData?

### ISSUE THREAD

**Issue by loxator** [xchainjs/xchainjs-lib#656]
Hello, I am trying to debug an issue while receiving transactions after a swap. I have swapped `Native RUNE` to `FOX Synth` and expected the transaction data to have this information while called `getTransaction`. However I only get the following data 
```
{
    "hash": "61559D65EE6D538032C2A42CB9F02B78B88631C80F958F0AAAF871279EBEE7E5",
    "asset": {
        "chain": "THOR",
        "symbol": "RUNE",
        "ticker": "RUNE",
        "synth": false
    },
    "from": [
        {
            "amount": {
                "type": "BASE",
                "decimal": 8
            },
            "from": "thor1fnpz2udh9vvzqc4uzz63fxzn8lnh6663zl8r44"
        },
        {
            "amount": {
                "type": "BASE",
                "decimal": 8
            },
            "from": "thor1fnpz2udh9vvzqc4uzz63fxzn8lnh6663zl8r44"
        }
    ],
    "to": [
        {
            "amount": {
                "type": "BASE",
                "decimal": 8
            },
            "to": "thor1dheycdevq39qlkxs2a6wuuzyn4aqxhve4qxtxt"
        },
        {
            "amount": {
                "type": "BASE",
                "decimal": 8
            },
            "to": "thor1g98cy3n9mmjrpn0sxmn63lztelera37n8n67c0"
        }
    ],
    "date": "2022-10-07T09:00:23.000Z",
    "type": "transfer"
}
```

If you check the hash on [viewblock](https://viewblock.io/thorchain/tx/61559D65EE6D538032C2A42CB9F02B78B88631C80F958F0AAAF871279EBEE7E5), we can see the correct data. I

s there any reason for why the transaction data comes out like this? Thanks for your help!

https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain/src/client.ts#L383

**Comment by veado** [comment]
@loxator Thanks for reporting. It looks like `getTransaction` does not support `synths` properly.

Are you able to fix it? Hint: In `utils` you will find helpers [`assetFromDenom`](https://github.com/xchainjs/xchainjs-lib/blob/d1c9acbdf8420c7356676161479c9635ddf64efc/packages/xchain-thorchain/src/util.ts#L50-L53) and [`getBalance`](https://github.com/xchainjs/xchainjs-lib/blob/d1c9acbdf8420c7356676161479c9635ddf64efc/packages/xchain-thorchain/src/util.ts#L384-L402). Both might be helpful to see how to get data for synths.

**Comment by loxator** [comment]
@veado Thanks for replying! I have added a fix on my end by extracting the function logic. I will try to create a PR with a similar logic against this repo, hopefully soon!
