### ISSUE TITLE
[xchain\bitcoin] maximum memo length 80 - this is incorrect

### ISSUE THREAD

**Issue by tonik-ru** [xchainjs/xchainjs-lib#699]
`  if (memo && memo.length > 80) `

this check will fail if you swap BTC->ETH.USDC

**Comment by mikewyszinski** [comment]
so AFAIK the 80 char limit is a hard limit of all BTC OP_RETURN, so we enforce it in the lib.

as far as thorchain memos go we have login in xchain-thorchain-query to construct appropriate memos and do our best to trim them for BTC see https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain-query/src/thorchain-query.ts#L310

i would encourage you to use the xchain-thorchain-query and/or xchain-thorchain-amm packages to implement thorchain actions (swap, add/remove LP etc) 

have a look at the examples folder for some illustrative samples  that use these 2 libs
https://github.com/xchainjs/xchainjs-lib/tree/master/examples

**Comment by tonik-ru** [comment]
once more:  if you trim to 80 chars, you WILL NOT be able to swap btc->usdc
i took you doSwap.ts and called it with btc->usdc args.
produced memo after estimate swap: '=:ETH.USDC-0XA0B86991C6218B36C1D19D4A2E9EB0CE3606EB48:0x5bdAbd971f74a19A1F7f9F1F135D76652953D0C2'
this is 96 chars. and its crashing inside swap. 
as you can see [https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain-query/src/thorchain-query.ts#L310](https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-thorchain-query/src/thorchain-query.ts#L310) will not help

**Comment by mikewyszinski** [comment]
for erc-20/bep2 assets you do not need to send in a complete address, just the first 6 chars after the - should be fine

for more info->  https://dev.thorchain.org/thorchain-dev/concepts/memos#asset-abbreviations

If you are using xchain-thorchain-query, i'll create a PR so that it shortens asset names to 6 characters after the '-' 
ex. ETH.USDC-0XA0B8

fix should be out in the next release

**Comment by mikewyszinski** [comment]
the swap memo should use the abreviated form now
