### ISSUE TITLE
review all xchainClient implementations for consistency

### ISSUE THREAD

**Issue by mikewyszinski** [xchainjs/xchainjs-lib#704]
There are slight variations among xchain implementations (different function arguments, parameters that are ignored, etc) , we should do the following:

- [ ] write a new  test (e2e or unit) suite that exercises every function in xchainClient interface for all clients
    -  note: thorchain-amm is probably the best place to write this test since it already has all the dependecies 
- [ ] try to rectify any inconsistencies found in implementations
   -  ideally, all clients should behave the same way and encapsulate any chain specific implementation differences

**Comment by GrassRootsCrypto** [comment]
https://github.com/xchainjs/xchainjs-lib/blob/multichain-wallet-example/examples/multi-chain-wallet/multi-chain-wallet.ts has the first part. 

For Part 2
1. queryAllFeeData is different for EVM chains, needs the params, wallet balance and address to send to. Only does transfer cost.
