### ISSUE TITLE
[BUG] Avalanche RPC blocked with a CORS error

### ISSUE THREAD

**Issue by 0xAzureDev** [xchainjs/xchainjs-lib#747]
## Description

When attempting to use the Avalanche Chain RPC in the `xchain-avax` package, I receive the following error message: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.avax.network/ext/bc/C/rpc. (Reason: CORS preflight response did not succeed). Status code: 403." This error occurs in the `const.ts` file located at `packages > xchain-avax > src > const.ts`. 

## Steps to reproduce

1. Create a next js project with `npx create-next-app@latest`.
2. Import the `@xchainjs/xchain-avax` package.
3. Import the package and initialize it.

## Expected behavior

The Avalanche Chain RPC should work as expected, not return any errors and allow me to transact.

## Actual behavior

The Avalanche Chain RPC returns the error message described above.

## Environment

- Package version: 0.1.7
- Framework: Nextjs 13.2.4

## Solution

The issue can be resolved by changing the RPC value of the `AVALANCHE_MAINNET_ETHERS_PROVIDER` constant

<https://github.com/xchainjs/xchainjs-lib/blob/07ebeb95eed180382d3aeaf9db01a6f6b99a9db2/packages/xchain-avax/src/const.ts#L26-L26>

to something like: 

`const AVALANCHE_MAINNET_ETHERS_PROVIDER = new ethers.providers.JsonRpcProvider('https://rpc.ankr.com/avalanche')`

The Ankr RPC is a lot more reliable based on my experience.

## Additional Information

To fully address this issue, users should be able to pass in an RPC with the client, or by falling back to other RPC URLs until an RPC works in the event of some RPC downtime.

**Comment by mikewyszinski** [comment]
changed defaults to use ankr. BTW you can always choose not to use the defaults and create your own configuration to init  client
