### ISSUE TITLE
Client improvements / suggestions

### ISSUE THREAD

**Issue by GrassRootsCrypto** [xchainjs/xchainjs-lib#755]
1. Create accessible default params for each client. Currently missing for cosmos, thorchain, Maya and Ethereum clients. E.g. default[chain]Params. I know AsgardEx manually sets the chain data, endpoints and so on, so being able to read the default parms and ensure they align against what you want is also good. 
2. Capitalisation of default params should be consistent. UXTOs are all caps and EVM are camel case  (see below)
3. Make client name accessible. Exposing `chain` within `BaseXChainClient` would work (but also require adding a `getChain(): Chain` to each client. This will allow a user to do `client.getChain()` to know what client they are dealing with or help with chain comparison. `IsTHORChain(client.getChain())`. 
4. Add `Maya` to the `Wallet` Class
5. Having issues getting data from AVAX and BSC Chain, get 'Invalid API Key' and `Caught TypeError: array.filter is not a function` see Run https://replit.com/@thorchain/xchain-evm#index.ts for more details. 
Not needed as API Key will fix it
7. Ensure `gasAssetDecimals` is set and exposed on all assets. It is done in EVM but not in other clients yet `export const DECIMAL = 8` is declared in the consts.ts of Maya and THORChain (which should be renamed), `LTC_DECIMAL = 8` in ltc, export const `BTC_DECIMAL = 8` in btc and so on. Looking for constancy really. `ETH_Decimal` is also in ETH but `AVAX_Decimal` is not in Avax (but `AVAX_GAS_ASSET_DECIMAL` is. Doing `client.gasAssetDecimals()` would be great :) and If I can do `client.getChain()` I know the chain I am talking about when working with many clients. 
Will add to xchain client interface `getAssetInfo()` which returns asset and decimals. 

```// UXTXO Clients
  const settings = { network: Network.Mainnet, phrase: phrase }
  const btcClient = new BTCClient ({  ...defaultBTCParams,  network: settings.network, phrase: settings.phrase}) // Bitcoin  
  const ltcClient = new LTCClient({   ...defaultLTCParams, network: settings.network, phrase: settings.phrase}) // Litecoin  
  const bchClient = new BCHClient({   ...defaultBCHParams, network: settings.network, phrase: settings.phrase }) // Bitcoin Cash
  const dogeClient = new DogeClient({ ...defaultDogeParams, network: settings.network, phrase: settings.phrase }) // Doge Coin     
  // Cosmos based clients
  const cosmosClient = new CosmosClient(settings) // Cosmos
  const thorClient = new THORClient(settings) // THORChain
  const mayaClient = new MayaClient(settings) // Maya
  // EVM Clients
  const ethClient = new ETHClient(settings) // Ethereum
  const avaxClient = new AvaxClient({ ...defaultAvaxParams, network: settings.network, phrase: settings.phrase }) // Avax
  const bscClient = new BSCClient({   ...defaultBscParams, network: settings.network, phrase: settings.phrase }) // Binance Smart Chain
  // Binance by itself ;)
  const bnbClient = new BNBClient(settings) // Binance
```

**Comment by Thorian1te** [comment]
Avax and Bsc work fine. 
- [ ] Accessible Default Params for every client 
- [ ] Check use of Camel case throughout library 
- [ ] Add Maya to wallet class
