### ISSUE TITLE
[tests] Mock real API calls for xchain-bitcoin 

### ISSUE THREAD

**Issue by thatStrangeGuyThorchain** [xchainjs/xchainjs-lib#77]
there should not be real API calls at test environment 'cause of theirs unpredictability

**Comment by thatStrangeGuyThorchain** [comment]
Also unskip unreliable commented test for client
https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-bitcoin/__tests__/client.test.ts#L115

**Comment by Thorian1te** [comment]
Closing this issue as mock tests were added along the way
