### ISSUE TITLE
Add Chain ID checks

### ISSUE THREAD

**Issue by GrassRootsCrypto** [xchainjs/xchainjs-lib#781]
As discussed with hodr, add checks to for the chainID in packages such as THORChain and Maya. Also, add an override option if someone wanted to connect to an older chain on an archive node. 

This will mean the thorchain package would auto update after the thorchian chain hard forks (which it does about once a year). 

THORChain is just an example, same applies to other chains that hard fork.

**Comment by Thorian1te** [comment]
there is already functionality to fetch the chainId
