### ISSUE TITLE
Integration of Round-Robin Providers in EvmClient 

### ISSUE THREAD

**Issue by hippocampus-web3** [xchainjs/xchainjs-lib#809]
The proposal aims to extend the functionality of round-robin providers from the UTXOClient to the EvmClient by creating corresponding functions for managing EVM-based wallets. These new functions, modeled after existing UTXOClient functions, would improve the resilience of data query requests by encouraging more interfaces to use xchain as their framework.

Additionally, the proposal includes the creation of a new package, xchain-evm-providers, centralizing all EVM-type providers. This unification mirrors the organization of UTXO chains, leading to a more coherent and scalable architecture.

The practical application of this is that we currently support two providers, etherscan and covalent, which together can offer a better user experience.

**Comment by Thorian1te** [comment]
Great addition to the xchainjs library. Lets get it done
