### ISSUE TITLE
Issue with xchain-litecoin and xchain-dogecoin

### ISSUE THREAD

**Issue by sectionshankar** [xchainjs/xchainjs-lib#816]
![image](https://github.com/xchainjs/xchainjs-lib/assets/38269146/de825510-233b-44fa-8cbe-39b698d66269)

I often receive these error in spite of having enough balance, most of the time with litecoin.
And also receiving no provider able to get GetUnspentTx

**Comment by Thorian1te** [comment]
@hippocampus-web3 
are you able to have a look at this one pls

**Comment by hippocampus-web3** [comment]
Yes, let me review it @Thorian1te

**Comment by hippocampus-web3** [comment]
Hello @sectionshankar,

Which data provider are you using for Litecoin and Dogecoin?

The error message `no provider available for GetUnspentTx` suggests that there's an issue with the data provider, probably the rate limits on their endpoints on the free tier.

By default, if you don't specify a provider when initializing the client, you'll be using Blockcypher. If you're not using a paid API key, you might be hitting their rate limit. You can review the [limitations](https://www.blockcypher.com/pricing.html) of their service here.

You have three options:

1. Modify your code to reduce the number of requests per second/day to stay within the free tier's rate limits.

2. Purchase a Blockcypher API key with a higher rate limit. Note that Xchain allows you to set a custom API key for data providers.

3. Alternatively, you can use [Sochain](https://sochain.com/api/) in place of Blockcypher. However, keep in mind that they don't offer a free tier, so you'll need to purchase an API key.

Please let me know if this clarifies things for your situation. If you need assistance with any of these solutions, don't hesitate to reach out.

**Comment by hippocampus-web3** [comment]
I closed the issue, if you have any problem related to that don't hesitate to reopen it. Thanks! @sectionshankar

**Comment by hippocampus-web3** [comment]
I think the reason is the same, the problem with rate limit in API providers but the error message 'Insufficient balance' is not descriptive we will improve the error message for that case

**Comment by sectionshankar** [comment]
@hippocampus-web3 @Thorian1te any work on this? Fixing or improving the message?

**Comment by hippocampus-web3** [comment]
Thanks for the reminder. Let me reopen this issue and address an improvement on the messages right now

**Comment by hippocampus-web3** [comment]
@sectionshankar Finally a deeper problem with UTXOs spending has been found and solved, there is still a bug to be solved in case you want to [spend the total funds](https://github.com/xchainjs/xchainjs-lib/issues/845) in the wallet but for the rest of the cases you should no longer get the error message 'Insufficient funds' if there are funds in the wallet. The change will be published with the next version, Thanks for reporting this bug 🙏
