### ISSUE TITLE
ADD: Fail over base url for Midgard-query 

### ISSUE THREAD

**Issue by Thorian1te** [xchainjs/xchainjs-lib#835]

**Comment by Thorian1te** [comment]
I made a change to the Midgard-query package so that if Midgard 9R endpoint fails then it will try thorswap Midgard but since this end point is blocking requests `export declare const MIDGARD_API_TS_URL = "https://midgard.thorswap.net/";` 
I am dubious about adding this change.  
@hippocampus-web3 
I am thinking about hosting a Midgard endpoint just for xchain/asgard

**Comment by hippocampus-web3** [comment]
@Thorian1te what about this issue, it is still necessary ?

**Comment by Thorian1te** [comment]
nah lets remove it
