### ISSUE TITLE
Add: Support for wallets without seedphrases for MAYAChain and THORChain

### ISSUE THREAD

**Issue by GiMa-Maya** [xchainjs/xchainjs-lib#861]
A wallet is trying to integrate Maya protocol. 

It is facing a problem, since not all accounts have a seed phrase, hence:
Can you make changes in the transfer method (https://github.com/xchainjs/xchainjs-lib/blob/4860de136791b490b36c1df81b63e4ca0de57589/packages/xchain-mayachain/src/client.ts#L540) to make it work with a private key incase account don't have a phrase with them?

This would apply to Maya as well as THORChain.

Full conversation:

> I don't think, we can send tokens using only these utils functions. As, I have to kind of recreate this class (https://github.com/xchainjs/xchainjs-lib/blob/4860de136791b490b36c1df81b63e4ca0de57589/packages/xchain-mayachain/src/client.ts#L79) to use all the methods that we are using in the transfer method (https://github.com/xchainjs/xchainjs-lib/blob/4860de136791b490b36c1df81b63e4ca0de57589/packages/xchain-mayachain/src/client.ts#L540) to make it work for a Private Key wallet. 
I can recreate this, but then whenever you will do any change I have to copy those changes on my end, and that doesn't seem to be a good idea.

> Can you make changes in the transfer method (https://github.com/xchainjs/xchainjs-lib/blob/4860de136791b490b36c1df81b63e4ca0de57589/packages/xchain-mayachain/src/client.ts#L540) to make it work with a private key incase we don't have a phrase with us?

**Comment by hippocampus-web3** [comment]
Now that prepareTx() support is available, this is now possible :)
