### ISSUE TITLE
Improve fee calculation strategy on Ethereum

### ISSUE THREAD

**Issue by hippocampus-web3** [xchainjs/xchainjs-lib#872]
From Discord discussion: https://discord.com/channels/838986635756044328/1165444263157436427

**Improvements**

- [x] `StantardFee` strategy to estimate `average` and `fastest` fee doesn't make sense, at least for the current state of ETH https://github.com/xchainjs/xchainjs-lib/blob/7b755eb89df9314cd7d8757c8f70f3a10ff0206b/packages/xchain-client/src/feeRates.ts#L7

- [x] Currently fees on EVM are always estimated using THORChain endpoint, that is the recommended gasRate for interact with THORChain network, but it's not functional for users that use the package as a wallet to do regular actions in the blockchains.

- [x] Support transactions using EIP 1559 for ETH

**Comment by 0xp3gasus** [comment]
I can take care of it
