### ISSUE TITLE
Rune Tx Issue

### ISSUE THREAD

**Issue by GrassRootsCrypto** [xchainjs/xchainjs-lib#889]
RUNE txs sometimes give the following error

```
{
  "tx_response": {
    "height": "0",
    "txhash": "0Fxyz",
    "codespace": "sdk",
    "code": 32,
    "data": "",
    "raw_log": "account sequence mismatch, expected 30, got 29: incorrect account sequence",
    "logs": [
    ],
    "info": "",
    "gas_wanted": "0",
    "gas_used": "0",
    "tx": null,
    "timestamp": "",
    "events": [
    ]
  }
```
See Discord for more details. 
https://discord.com/channels/838986635756044328/1168595765065691259/1168706720994955274

**Comment by Thorian1te** [comment]
not sure if this is still an issue I have not seen this error in a while

**Comment by matikucharski** [comment]
> not sure if this is still an issue I have not seen this error in a while

It is still the issue

**Comment by Thorian1te** [comment]
Hi, this issue isn't with this package it is due to nineRealms (9R) aggressively caching endpoints. Hence the reason why the sequence takes a while to update

**Comment by matikucharski** [comment]
@Thorian1te Is there a way to resolve this? Specify other endpoint? But I guess this requires to have my own thorchain node to query?

**Comment by Thorian1te** [comment]
Yes you'll need your own node to query. 
Ive spent many hrs thinking about this, here are the other options
- manually increment sequence, will require fetching the sequence first before sending Tx. 
- creating a sequence cache
- querying your own node
- Adding a check in thorchain package that checks to see if the sequence matches if not increment by 1 before completing transfer | deposit.
