### ISSUE TITLE
Snowtrace will be discontinued

### ISSUE THREAD

**Issue by 0xp3gasus** [xchainjs/xchainjs-lib#892]
I saw Snowtrace is going to be discontinued on Nov 30th, so AVAX providers will be affected, I think it would be great to elaborate an action plan to be ready for this change

**Comment by hippocampus-web3** [comment]
Yes, it really is something we have to change as soon as possible, do you want to take care of this issue ?

**Comment by 0xp3gasus** [comment]
For sure, I can take care of it  🦾
