### ISSUE TITLE
FIX: Avax chain

### ISSUE THREAD

**Issue by Thorian1te** [xchainjs/xchainjs-lib#925]
Ajax online provider still point to snow trace.io ? - probably should update this as that endpoint no longer works 
the fix > https://snowtrace.dev ? 
```const AVAX_ONLINE_PROVIDER_TESTNET = new EtherscanProvider(
  AVALANCHE_TESTNET_ETHERS_PROVIDER,
  'https://api-testnet.snowtrace.io',
  process.env['SNOWTRACE_API_KEY'] || '',
  AVAXChain,
  AssetAVAX,
  18,
)
const AVAX_ONLINE_PROVIDER_MAINNET = new EtherscanProvider(
  AVALANCHE_MAINNET_ETHERS_PROVIDER,
  'https://api.snowtrace.io',
  process.env['SNOWTRACE_API_KEY'] || '',
  AVAXChain,
  AssetAVAX,
  18,
)
```

**Comment by 0xp3gasus** [comment]
Explorers were updated in #892 as this [line](https://github.com/xchainjs/xchainjs-lib/blob/b7bc9656dd065a94525cfeae063e489056b77bf0/packages/xchain-avax/src/const.ts#L87) shows. AVAX is already using snowtrace.dev as Explorer, so *getExplorerUrl*, *getExplorerAddressUrl* and *getExplorerTxUrl* will return the endpoints with the new explorer. 

On the other hand, we have the data explorers, Avax is now using Snowtrace with Etherscan evm-provider and Routescan evm-provider. The one you mention will be deprecated by the end of month, but it is still available.

**Comment by Thorian1te** [comment]
okay closing issue then
